version: '3.1'
services:
  mongo:
    image: 'mongo:4.2.11-bionic'
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=testDb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - DB_NAME=testDb
      - DB_USER=testUser
      - DB_PASSWORD=testPassword
    ports:
      - 27017:27017
    volumes: 
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
